# Generated by Django 2.1.2 on 2018-11-01 15:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acc_num', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('balance', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('pending', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete='PROTECT', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('pending', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete='PROTECT', related_name='owner_d', to=settings.AUTH_USER_MODEL)),
                ('owner_acc', models.ForeignKey(on_delete='PROTECT', related_name='owner_acc_d', to='bank.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('message', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('private_key', models.CharField(max_length=512)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField()),
                ('pending', models.BooleanField(default=True)),
                ('receiver', models.ForeignKey(on_delete='PROTECT', related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('receiver_acc', models.ForeignKey(on_delete='PROTECT', related_name='receiver_acc', to='bank.Account')),
                ('sender', models.ForeignKey(on_delete='PROTECT', related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('sender_acc', models.ForeignKey(on_delete='PROTECT', related_name='sender_acc', to='bank.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('pending', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete='PROTECT', related_name='owner_w', to=settings.AUTH_USER_MODEL)),
                ('owner_acc', models.ForeignKey(on_delete='PROTECT', related_name='owner_acc_w', to='bank.Account')),
            ],
        ),
        migrations.AddField(
            model_name='access',
            name='acc_num',
            field=models.ForeignKey(on_delete='PROTECT', to='bank.Account'),
        ),
        migrations.AddField(
            model_name='access',
            name='access_req',
            field=models.ForeignKey(on_delete='PROTECT', related_name='wants_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='access',
            name='owner',
            field=models.ForeignKey(on_delete='PROTECT', related_name='is_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
