# Generated by Django 2.1.2 on 2018-10-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_num',
            field=models.UUIDField(default=35156830662598496897813049306399452561, editable=False, unique=True),
        ),
    ]
