# Generated by Django 2.1.2 on 2018-10-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
