# Generated by Django 2.1.2 on 2018-10-31 21:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20181031_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_num',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
