# Generated by Django 2.1.2 on 2018-11-01 07:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0003_auto_20181031_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('pending', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete='PROTECT', related_name='owner_d', to=settings.AUTH_USER_MODEL)),
                ('owner_acc', models.ForeignKey(on_delete='PROTECT', related_name='owner_acc_d', to='bank.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('pending', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete='PROTECT', related_name='owner_w', to=settings.AUTH_USER_MODEL)),
                ('owner_acc', models.ForeignKey(on_delete='PROTECT', related_name='owner_acc_w', to='bank.Account')),
            ],
        ),
    ]
