# Generated by Django 2.1.2 on 2018-11-01 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_deposit_withdraw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pending',
            name='choice',
        ),
    ]
