# Generated by Django 2.1.2 on 2018-11-01 16:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0005_remove_pending_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPInfo',
            fields=[
                ('trans_id', models.IntegerField(primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=6)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='pending',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
