# Generated by Django 2.1.2 on 2018-10-30 23:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trans',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete='PROTECT', to=settings.AUTH_USER_MODEL),
        ),
    ]
